// Export the type definitions so they can be merged into the main server configuration
// We define the strict contract that the Next.js frontend must follow
export const typeDefs = `#graphql
  # ---------------------------------------------------------
  # CUSTOM SCALARS
  # ---------------------------------------------------------
  # We define a custom DateTime scalar because standard GraphQL only supports basic strings/ints
  scalar DateTime

  # ---------------------------------------------------------
  # TYPES (The exact shape of the data returned to the UI)
  # ---------------------------------------------------------
  
  # The 'Document' type represents a file uploaded for AI vectorization
  type Document {
    # 'ID!' means a unique identifier that is strictly required (cannot be null)
    id: ID!
    # The name of the file, required for UI display
    filename: String!
    # The async processing state (e.g., 'PENDING', 'PROCESSING', 'COMPLETED')
    status: String!
    # The exact time the upload occurred, using our custom DateTime scalar
    uploadedAt: DateTime!
  }

  type DocumentMetadata {
    id: String!
    filename: String!
  }

  # The 'CopilotResponse' type represents the answer returned by the LangGraph AI
  type CopilotResponse {
    # The actual text answer generated by the LLM
    answer: String!
    # An array of strings representing the document IDs used as context (RAG)
    sources: [String!]!
    # A boolean flag to tell the UI if this answer was pulled instantly from Redis cache
    isCached: Boolean!
  }


  type AICacheResponse {
    answer: String!
    sources: [String!]!
    isCached: Boolean!
  }

  # 👉 NEW: The exact shape of the data returning from our gRPC microservice
  type AccessResponse {
    isAuthorized: Boolean!
    message: String!
  }

  # ---------------------------------------------------------
  # QUERIES (Synchronous Reads - Fetching Data)
  # ---------------------------------------------------------
  type Query {
    # Fetches the current processing status of a document via the Identity/Ingestion DBs
    getDocumentStatus(documentId: ID!): Document

    # Sends a question to the AI Copilot. It requires a documentId for context and the question string.
    # askCopilot(documentId: ID!, question: String!): CopilotResponse!
    askCopilot(documentId: ID!, question: String!): AICacheResponse

    # 👉 NEW: The UI will call this to check permissions
    verifyAccess(userId: String!, role: String!): AccessResponse
    
    getUploadedDocuments: [DocumentMetadata!]!
  }

  # ---------------------------------------------------------
  # MUTATIONS (Asynchronous Writes - Changing Data)
  # ---------------------------------------------------------
  type Mutation {
    # Uploads a document. It returns the 'Document' type so the UI immediately gets the new ID and 'PENDING' status.
    uploadDocument(filename: String!, contentBase64: String!): Document!
  }
`;